In [1]:
import torch
import torch.nn as nn

In [2]:
a = torch.randn(1,1,2,2); a

tensor([[[[-0.4124, -0.3257],
          [-0.6939, -1.4715]]]])

In [4]:
y = nn.AvgPool2d(kernel_size=2)

In [5]:
y(a)

tensor([[[[-0.7258]]]])

In [8]:
b = torch.randn(2,1,5,5); b

tensor([[[[-0.0777,  1.0707, -0.0845, -0.4380, -0.8027],
          [-0.3297, -0.4995, -0.1945, -1.0740, -0.6072],
          [ 0.6832,  0.9274, -1.0027,  0.0887,  0.1390],
          [-0.7349, -0.0810,  1.5854,  0.1384, -1.5997],
          [-0.7021, -1.0962, -0.6761,  0.3862,  0.5413]]],


        [[[-1.0923,  0.9377,  1.4806, -0.9933, -0.5350],
          [ 1.5941,  0.5890,  0.0889, -1.9669,  0.4439],
          [ 1.0133, -1.2344, -0.8313,  1.5950, -0.9545],
          [-0.8553, -0.5280,  1.6119,  1.1269,  1.1266],
          [ 0.4212, -0.3768, -0.8885,  0.0140, -0.2190]]]])

In [10]:
y(b)

tensor([[[[ 1.0707, -0.0845],
          [ 0.9274,  1.5854]]],


        [[[ 1.5941,  1.4806],
          [ 1.0133,  1.6119]]]])

In [11]:
from PIL import Image
import numpy as np

In [12]:
img = Image.open("pics/file_0_5.png")
img.load()
img = np.asarray( img, dtype="int32" )
print(img)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 18

In [15]:
for row in img:
    for val in row:
        print("%3d " % val, end='')
    print()

  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 
  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0 
  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0 
  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0 
  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 182 247 241   0   0   0   0   0   0 

In [18]:
with open("pics/file_0_5.pgm", "w") as file:
    file.write("P2\n")
    file.write("# Generated by test.ipynb for ece496\n")
    file.write("28 28\n")
    file.write("255\n")
    for row in img:
        for val in row:
            file.write("%d " % val)
        file.write("\n")

In [19]:
with open("pics/test.pgm", "w") as file:
    file.write("P2\n")
    file.write("# Generated by test.ipynb for ece496\n")
    file.write("28 28\n")
    file.write("255\n")
    i = 1
    for row in img:
        for val in row:
            file.write("%d " % i)
            i = i+1
        file.write("\n")

In [20]:
with open("pics/test1.pgm", "w") as file:
    file.write("P2\n")
    file.write("# Generated by test.ipynb for ece496\n")
    file.write("28 28\n")
    file.write("255\n")
    for row in img:
        for val in row:
            file.write("%d " % 1)
        file.write("\n")